docker-vumi-metrics:
    build: .
    ports:
     - "9108:9108"
    volumes:
     - example-app:/app
    links:
     - rabbitmq
     environment:
      - AMQP_HOST=rabbitmq
rabbitmq:
    image: rabbitmq